default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: db

development:
  <<: *default
  database: backend_development

test:
  <<: *default
  database: <%= ENV['DB_DATABASE'] || 'backend_test' %>
  username: <%= ENV['DB_USERNAME'] || ENV['MYSQL_USER'] %>
  password: <%= ENV['DB_PASSWORD'] || ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] || 'db' %>

production:
  <<: *default
  database: <%= Rails.application.credentials.db[:database] %>
  username: <%= Rails.application.credentials.db[:username] %>
  password: <%= Rails.application.credentials.db[:password] %>
  host: <%= Rails.application.credentials.db[:host] %>
