version: '3'

services:
  back:
    build: ./backend
    command: /bin/bash -c "rm -rf tmp/pids/server.pid; bundle exec rails s -p 3000 -b 0.0.0.0"
    ports:
      - '3000:3000'
    env_file:
      - ./db/db.env
    tty: true
    stdin_open: true
    volumes:
      - ./backend:/app/backend
      - bundle:/usr/local/bundle
    depends_on:
      - db
  db:
    build: ./db
    ports:
      - '3306:3306'
    env_file:
      - ./db/db.env
    volumes:
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
  front:
    build: ./frontend
    command: /bin/bash -c "npm run serve"
    ports:
      - '8080:8080'
    tty: true
    stdin_open: true
    volumes:
      - ./frontend:/app/frontend
volumes:
  bundle:
  db-data:
