# inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
      - 'Gemfile'
      - 'app/mailers/application_mailer.rb'
      - 'bin/*'
      - 'db/schema.rb'
      - 'config/*'
      - 'config/environments/*'
      - 'config/initializers/cors.rb'
      - 'spec/*_helper.rb'
      - 'vendor/**/*'
      - 'config.ru'
      - 'Rakefile'

Style/FrozenStringLiteralComment: # 変数をmutable(=変更できる)な値に定義
    Enabled: false

Style/Documentation: # classやmoduleのトップレベルのドキュメントをチェック
    Enabled: false

Style/EmptyMethod: #空メソッドのフォーマット
    EnforcedStyle: expanded

Style/StringLiterals: # 文字列を囲むクォーテーション
    EnforcedStyle: double_quotes

Style/AsciiComments: # 日本語のコメント
  Enabled: false

Metrics/AbcSize: # 代入(A)、メソッド呼び出し(B)、条件式(C)の数を数え、それぞれの2乗の和の平方根の大きさ
    Max: 24

Metrics/ClassLength: # クラスの長さ
    Max: 110

Metrics/MethodLength: # メソッドの長さ
    Max: 30

Layout/IndentationConsistency: # private, protected配下のメソッドのインデント
    EnforcedStyle: indented_internal_methods

Style/RegexpLiteral: # 正規表現の記法 %r or / /
    Enabled: false

Style/SymbolArray: # シンボルの記法 %i or [ ]
    Enabled: false

Style/PercentLiteralDelimiters: # %記法の区切り文字を指定
  PreferredDelimiters:
    default: '[]'
    # '%w': '()'  ex) %w(_ -) -> ["_", "-"]

Style/SymbolProc: # something.map { |s| s.upcase }
    Enabled: false

Naming/VariableNumber:
    EnforcedStyle: snake_case

Rails/InverseOf:
    Enabled: false
